from flask import Flask, request, jsonify
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from flask_cors import CORS
import joblib

app = Flask(__name__)
CORS(app)  # Enable Cross-Origin Requests


data = {
    "Input": [
        "Can you recommend something for my bone health?",
"My joints keep cracking, what can I do about that?",
"I’ve been feeling a lot of joint stiffness lately.",
"Do you have anything for flexibility and joint pain?",
"Been having some discomfort in my knees, anything I can take?",
"My bones feel weak, anything to help with that?",
"Looking for something to help with joint mobility.",
"Do you have any supplements for joint pain relief?",
"My hands are starting to ache, what can I take?",
"Any good products to keep my bones strong and healthy?",
"I’ve been feeling sore in my joints, any recommendations?",
"Can you help me find something for joint support?",
"My back has been hurting a lot lately, anything for that?",
"Is there something to make my bones stronger?",
"I need something for my aching knees, what do you suggest?",
"I’ve been getting some joint pain after workouts, any advice?",
"Anything that helps with bone health and mobility?",
"I’m looking for a supplement for my bone health.",
"My elbows have been stiff, what can I do?",
"Got anything for joint discomfort and flexibility?",
"My knees are always stiff, what can I take for that?",
"I’ve been feeling some joint pain lately, any products for that?",
"Is there a supplement that helps with bone strength?",
"My joints crack a lot, is that normal? Any solutions?",
"Can you recommend something for my osteoarthritis?",
"I need something for my joints after heavy lifting, got any ideas?",
"Do you have anything that can help with bone pain?",
"I’m looking for something to keep my joints healthy as I get older.",
"Anything to help with cartilage repair or bone health?",
"My lower back has been bothering me, can you help with that?",
"My joints hurt, what can I take?",
"Do you have anything for bone health?",
"I need something for my sore knees.",
"Any supplements for joint pain?",
"Looking for something to help my joints feel better.",
"My bones feel weak, any recommendations?",
"Can you help with stiff joints?",
"Is there a product for joint mobility?",
"Do you have anything for hip pain?",
"I need something to support my joints.",
"My joints are always aching, got any products for that?",
"Anything for improving bone strength?",
"I need something to ease my joint stiffness.",
"Can you recommend something for knee pain?",
"Any supplements to help with bone density?",
"Looking for something to support my joints as I age.",
"My elbows hurt, do you have anything for that?",
"Got anything to relieve joint discomfort?",
"I’ve been dealing with joint pain for a while, any advice?",
"Can you suggest something for bone and joint health?",
"Do you have anything for joint inflammation?",
"My bones feel weak lately, can you help?",
"I'm looking for something to support joint mobility.",
"Need a product for sore joints and bones.",
"Got anything to relieve arthritis pain?",
"Can you recommend a supplement for bone health?",
"My joints crack a lot, is there anything for that?",
"Looking for something to improve joint flexibility.",
"Any advice for strengthening my bones?",
"I'm having trouble with my joints, need something for relief.",
"Looking for something to help with joint stiffness.",
"Can you suggest something for my bone health?",
"Do you have anything for joint pain relief?",
"Need help with improving my bone strength.",
"Can you recommend a supplement for joint flexibility?",
"My knees hurt, anything you can suggest?",
"Any products for sore joints after a workout?",
"Looking for a product that helps with bone density.",
"Do you have anything for arthritis relief?",
"Anything that can help with my weak joints?",
"I'm looking for something to support my joints.",
"Got any products for bone health?",
"My joints are aching, what can help?",
"Can you recommend something for joint pain?",
"I need a supplement for stronger bones.",
"Do you have any joint health products?",
"Can I get something for cartilage support?",
"Anything for treating arthritis pain?",
"Need a product that helps with bone healing.",
"Looking for something to improve joint mobility.",
"Any products to improve bone strength?",
"Looking for something for joint stiffness.",
"Do you have anything for my weak knees?",
"I need help with joint discomfort, any suggestions?",
"Can you recommend something for bone density?",
"Got any options for osteoarthritis relief?",
"Looking for a supplement that supports joints.",
"Do you sell anything for bone repair?",
"Need something to boost my joint flexibility.",
"Is there a product for bone health that you recommend?",
"Any good products for bone and joint pain?",
"I need something for joint inflammation.",
"Do you have anything to help with bone fragility?",
"I'm looking for a supplement for joint support.",
"Got any recommendations for aching knees?",
"Is there anything to strengthen bones and joints?",
"Do you have anything for joint pain relief?",
"Looking for products to help with joint mobility.",
"Can you suggest something for bone health?",
"Is there a good product for healthy joints?",
"Got anything for improving gut health?",
"I'm looking for something to help with digestion.",
"Do you have products that support gut health?",
"Any recommendations for bloating relief?",
"I need something for a healthier gut.",
"Looking for probiotics to improve digestion.",
"Do you have anything to support a healthy stomach?",
"I'm struggling with digestion, any products for that?",
"Is there anything to improve gut flora?",
"Any supplements for a healthy gut?",
"Do you have anything for gut health support?",
"I'm looking for something to help with my digestion problems.",
"Anything that can help with bloating and gut discomfort?",
"Got anything to boost my gut flora?",
"Any products to support a healthy stomach?",
"I'm searching for something to improve my digestive system.",
"Do you have probiotics for gut health?",
"Need something that helps with digestion and bloating.",
"Looking for something to improve my gut balance.",
"Do you have anything for a healthy gut microbiome?",
"Can you recommend something for a healthier gut?",
"I'm looking for something that helps with digestion issues.",
"Do you have anything for bloating and gut discomfort?",
"Any products that help improve gut health?",
"I need something for better digestion, do you have it?",
"Looking for a supplement to improve my gut health.",
"Can you suggest something for a more balanced gut?",
"I'm having stomach issues, any products that can help?",
"Do you have probiotics for a healthier digestive system?",
"Is there anything to help with gut balance and bloating?",
"Any recommendations for better digestion?",
"Can you suggest something for a happier gut?",
"I need something to help with my digestive system.",
"Do you have anything for bloating and digestive health?",
"Looking for something to improve gut function.",
"Any products that help with digestive balance?",
"Can you recommend a supplement for gut health?",
"I'm having issues with digestion, anything that can help?",
"Do you have anything that supports gut health and immunity?",
"I'm interested in probiotics for better digestion, got any?",
"I need something to improve my gut health.",
"Any products for bloating relief?",
"Looking for a supplement that helps digestion.",
"Can you suggest something for a healthier gut?",
"My gut has been feeling off, what can help?",
"Any gut health supplements you'd recommend?",
"I'm trying to improve my digestion, do you have anything?",
"Can you help me with products for better gut health?",
"I've been having digestion issues lately, any suggestions?",
"I'm thinking of adding something for gut health to my routine.",
"I'm looking for something to support my gut health.",
"Do you have anything that helps with indigestion?",
"I need help with bloating, any suggestions?",
"Looking for a gut-friendly supplement.",
"Can you recommend anything for digestive support?",
"I’ve been feeling sluggish, something for digestion?",
"What do you have for improving gut health?",
"Anything to help with gas and bloating?",
"I need a product that aids in digestion.",
"My gut needs some TLC, what should I take?",
"I need something to improve my digestion.",
"Anything for bloating and indigestion?",
"Can you recommend a product for gut health?",
"I'm feeling sluggish, need help with digestion.",
"Looking for a supplement to support my gut.",
"Do you have anything for bloating after meals?",
"Any suggestions for maintaining gut health?",
"Something for digestion would be great right now.",
"My gut has been off lately, what should I try?",
"Any products to help with gut and stomach issues?",
"I’ve been feeling constipated lately, any recommendations?",
"Looking for something to improve my gut health.",
"I’ve had some stomach issues, what can I take for it?",
"Need a product for better digestion.",
"Can you suggest something for bloating?",
"Something to help with gut health, please.",
"Any supplements for a healthier digestive system?",
"I’m dealing with acid reflux, what should I try?",
"Looking for something to regulate my digestion.",
"Can you recommend something for gut balance?",
"Can you suggest a product to help with digestive issues?",
"I’ve been having trouble with bloating, any advice?",
"Looking for something to help improve my gut flora.",
"Do you have anything for an upset stomach?",
"Been feeling sluggish, what can I take for digestion?",
"What supplements can help with my gut health?",
"I need help with my digestion, can you recommend something?",
"Is there something to support my gut after a heavy meal?",
"Can you suggest something for better gut function?",
"Anything to help with digestion and reduce bloating?",
"Can you recommend a supplement for better digestion?",
"Any products that can help with bloating after meals?",
"I'm looking for something to support my gut health.",
"Do you have any products for gut issues like discomfort?",
"Can I get help with improving my digestive system?",
"Is there a supplement that can help with bloating and gas?",
"I need something to improve my gut microbiome.",
"Do you have anything to aid digestion naturally?",
"What can help with my stomach after eating heavy food?",
"I’m struggling with digestion, any suggestions for gut health?",
"Can you suggest something to boost my immune system?",
"Do you have products to strengthen immunity?",
"I'm looking for supplements that support immunity.",
"Any recommendations for better immune health?",
"Can you help me find something to protect against colds?",
"What can I take to improve my immune function?",
"I need something to boost my immune response.",
"Can you recommend a product to help prevent illness?",
"I'm looking for a natural way to support my immune system.",
"Do you have any immune support supplements?",
"Which product helps in boosting immunity?",
"Do you have anything for strengthening the immune system?",
"I'm looking for natural supplements to support my immunity.",
"Any recommendations for improving my immune defense?",
"What can I take to enhance my body's immunity?",
"Can you suggest some immune system boosters?",
"I'm trying to find something to improve immune health.",
"Looking for products that help with immune support.",
"Can you recommend something to help me stay healthy and fight off illness?",
"What should I take to keep my immune system strong?",
"How can I improve my immune system?",
"Looking for something to boost my immunity.",
"Can you suggest something for strengthening my immune system?",
"Need help with boosting my immune system, especially during flu season.",
"Do you have any immune support products?",
"What's good for staying healthy and fighting off colds?",
"Can you recommend anything for better immunity?",
"I’ve been feeling a little run down lately, need immune support.",
"Any supplements to help with immunity?",
"What’s good to take for a stronger immune system?",
"Do you have anything for immune system support?",
"Looking for something to help boost my immunity.",
"Can you recommend immune boosters?",
"What can I take to improve my immune health?",
"Do you have products that support a strong immune system?",
"I need something to keep my immune system strong.",
"Is there anything I can take to prevent getting sick?",
"Can you suggest immune support supplements?",
"What's the best way to improve my immune function?",
"Can you help me with something to strengthen my immune system?",
"Any products to strengthen my immunity?",
"Looking for something to boost my immune system.",
"Got anything that helps with immunity?",
"Can you recommend something for a stronger immune system?",
"I need to boost my immune health, any suggestions?",
"What do you have for immune system support?",
"Anything that can help me stay healthy and fight off sickness?",
"Can you recommend a supplement for immune health?",
"Looking to support my immune system, what should I try?",
"What’s good for improving immune function?",
"Can you recommend something to boost my immunity?",
"Been catching every cold going around, any suggestions?",
"Need something for my immune system, it's been weak.",
"How do I stay healthy during flu season?",
"Can I get something that helps me fight infections?",
"Any good immune boosters I should try?",
"I feel like I’m always getting sick, need help.",
"Looking for something to support my immune health.",
"Can you help me with a product to strengthen my immune system?",
"Got anything to help me stay strong and avoid illness?",
"I’ve been feeling run down, any immune system products?",
"Looking for something to help with my immune system.",
"Anything to prevent getting sick all the time?",
"Can I get something to give my immune system a boost?",
"Do you have something to help with general health and immunity?",
"Need advice on strengthening my immune health.",
"Any good remedies to help my body fight off infections?",
"Can you recommend something to stay healthy during the colder months?",
"I’m always catching colds, can you help me out?",
"Looking for ways to keep my immune system strong, any suggestions?",
"I’m always tired and get sick easily, anything to help?",
"Can you recommend something for immune support?",
"I’m looking for ways to boost my immunity.",
"I’ve been getting sick a lot lately, any suggestions?",
"Any products to help me stay healthy during flu season?",
"Looking for a way to stay strong against infections.",
"Anything I can take to improve my immune system?",
"Can you help me stay healthy this winter?",
"I need something to keep my immune system in check.",
"Any tips on how to avoid getting sick often?",
"I keep getting colds, what can I take?",
"Anything to help me fight off infections?",
"I want to boost my immune system naturally.",
"Do you have anything for frequent illness?",
"How can I stay healthy during flu season?",
"I need something to improve my immunity.",
"Looking for immune system boosters, got any suggestions?",
"I always seem to catch something, help?",
"What can I take to prevent getting sick?",
"I’ve been run down lately, anything for immunity?",
"I’m always feeling a bit under the weather, what can help?",
"Got anything for a weak immune system?",
"How can I make sure I don’t get sick this winter?",
"Need something to keep me from catching colds all the time.",
"Can you recommend something to strengthen my immunity?",
"Always tired, should I be worried about my immune system?",
"What’s good for boosting my immune health?",
"I’ve been getting sick a lot lately, any immune support?",
"Is there something to make me more resistant to infections?",
"I need something to help my body fight off illnesses.",
"Do you have anything to boost my energy?",
"I feel so drained lately, need something for energy.",
"What's good for staying energized throughout the day?",
"Any supplements to help me feel more awake?",
"I need more energy for my workouts, can you help?",
"Can you recommend something for fatigue?",
"I’m always feeling tired, what can I take for more energy?",
"Is there anything to help me stay alert in the afternoons?",
"What’s the best energy booster for a busy day?",
"I need something to power through my day without feeling sluggish.",
"I'm feeling so drained lately, need something to boost my energy",
"Any suggestions for something that'll help with fatigue?",
"I get so tired during the day, what's good for that?",
"Can you recommend something for low energy levels?",
"Any energy supplements that actually work?",
"I need something to give me a little pick-me-up during work",
"Looking for a boost, what do you recommend for energy?",
"Been feeling sluggish, need some extra energy throughout the day",
"What's the best way to fight off tiredness and stay alert?",
"Need help staying awake at work, anything for energy?",
"I'm feeling so drained lately, need something to boost my energy",
"Any suggestions for something that'll help with fatigue?",
"I get so tired during the day, what's good for that?",
"Can you recommend something for low energy levels?",
"Any energy supplements that actually work?",
"I need something to give me a little pick-me-up during work",
"Looking for a boost, what do you recommend for energy?",
"Been feeling sluggish, need some extra energy throughout the day",
"What's the best way to fight off tiredness and stay alert?",
"Need help staying awake at work, anything for energy?",
"Is there anything that can help me feel more energized throughout the day?",
"I need a pick-me-up for my energy levels, any suggestions?",
"Been feeling so drained lately, what can I take to feel more alive?",
"Any good energy supplements to help me focus during long hours of work?",
"Looking for something to boost my energy for morning workouts",
"Feeling sluggish today, what can I take for a quick energy boost?",
"Anything that can help me feel awake and energized without caffeine?",
"Need something to keep me going through my busy day",
"Can you suggest any energy boosters to help me fight off fatigue?",
"Anything that can give me a bit more energy in the afternoons?",
"Can you recommend something that helps with low energy?",
"I need something to keep me awake and alert throughout the day.",
"What's good for boosting energy naturally?",
"Looking for something to fight off that mid-afternoon slump.",
"Been feeling tired all week, any energy supplements that can help?",
"Is there anything that can give me an energy boost without making me jittery?",
"Can you suggest something to help me power through my long work hours?",
"Is there a natural energy booster that’s safe to take daily?",
"Can I find something that will help me stay awake during my night shifts?",
"Any energy products that can help me get through a tough workout?",
"Looking for something that can help me stay energized all day.",
"Can you suggest something to boost my energy in the morning?",
"Feeling super sluggish lately, any products that can help?",
"I need something to fight fatigue and keep me going.",
"What's good for that energy dip I get around noon?",
"Any recommendations for a natural pick-me-up when I’m exhausted?",
"Is there something that can help me get through my busy day without crashing?",
"Can you recommend a supplement that helps with long-term energy?",
"I’m always tired, what should I take to feel more awake?",
"Any tips for staying energized during a stressful week?",
"Do you have anything to help boost my energy levels?",
"Looking for something to help me power through my workday.",
"Need a natural energy boost, what do you recommend?",
"Any suggestions for products that help with fatigue?",
"I’m always feeling drained, what can I take for more energy?",
"Looking for a supplement to help me stay focused and energized.",
"Can you recommend something for that afternoon energy slump?",
"What’s good for boosting energy without the crash?",
"Need help with staying energized throughout the day.",
"Any products to help me feel more awake in the mornings?",
"Got anything to help me stay awake and energized during the day?",
"I'm feeling so tired lately, any energy boosters you recommend?",
"Can you suggest something for a natural energy pick-me-up?",
"Looking for something to give me that extra energy in the morning.",
"Need an energy boost, but not a lot of caffeine.",
"Do you have something to help with my energy levels throughout the day?",
"Any vitamins or supplements that help with energy?",
"I'm dragging today, need something for energy!",
"Any products for quick energy that last longer than coffee?",
"I’m always tired, what can help me feel more energized?",
"Do you have anything that helps boost energy without the crash?",
"I'm feeling drained, need something to help me power through the day.",
"Looking for something that gives me energy without making me jittery.",
"Anything that can help me stay awake and focused during work?",
"I'm always tired after lunch, got any energy boosters?",
"Need an energy supplement for those long nights studying.",
"Can you recommend something to give me a natural energy boost?",
"I need something that’ll keep me energized all day long.",
"Any products that help with afternoon fatigue?",
"Looking for something that helps with energy, but no caffeine.",
"I'm feeling super sluggish, any energy supplements you recommend?",
"Do you have anything that helps with morning fatigue?",
"I'm always so tired, need something to keep me going throughout the day.",
"Looking for a product to give me energy during my workouts.",
"Do you have any energy boosters that are gentle on the stomach?",
"Can you recommend something for an afternoon energy slump?",
"I'm low on energy lately, got any natural options for me?",
"Anything that’ll help me focus and stay energized at work?",
"I’m feeling tired all the time, need something to perk me up.",
"Looking for a natural energy supplement that won’t give me the jitters.",
"Struggling to fall asleep lately, any suggestions for sleep aids?",
"Do you have anything to help with nighttime anxiety?",
"I need something to help me relax after a long day, any ideas?",
"Looking for a product that will help me sleep better at night.",
"Any natural sleep remedies you can recommend?",
"I can’t get good rest these days, what do you have for relaxation?",
"Do you have anything that helps with winding down before bed?",
"Looking for something to calm my mind and help me sleep.",
"Any tips for better sleep without feeling groggy in the morning?",
"I'm finding it hard to sleep through the night, got any products for that?",
"Can you suggest something to help me fall asleep faster?",
"I need something to calm my nerves before bed, anything you recommend?",
"Looking for a natural way to relax and get better sleep.",
"Do you have any sleep aids that aren’t too strong but work well?",
"Anything that can help me unwind after a stressful day?",
"I’ve been tossing and turning at night, got any products for that?",
"Do you have anything to help me relax without feeling drowsy during the day?",
"Looking for something that helps me sleep deeply and wake up refreshed.",
"I need a product that helps me relax and get better sleep, not sure where to start.",
"Any suggestions for sleep problems caused by stress?",
"Got any products to help me sleep better without the grogginess?",
"Any natural remedies to help me unwind before bed?",
"I’m having trouble sleeping lately, do you have anything that can help?",
"Looking for something to calm my mind at night.",
"I’ve been feeling stressed and restless at night, anything to help me sleep?",
"Can you recommend something to help me sleep through the night?",
"Anything for improving sleep quality and reducing stress?",
"Need help relaxing before bed, any products for that?",
"Got anything to make falling asleep easier?",
"Looking for something that helps me sleep soundly and wake up rested.",
"Got any products to help me sleep better without the grogginess?",
"Any natural remedies to help me unwind before bed?",
"I’m having trouble sleeping lately, do you have anything that can help?",
"Looking for something to calm my mind at night.",
"I’ve been feeling stressed and restless at night, anything to help me sleep?",
"Can you recommend something to help me sleep through the night?",
"Anything for improving sleep quality and reducing stress?",
"Need help relaxing before bed, any products for that?",
"Got anything to make falling asleep easier?",
"Looking for something that helps me sleep soundly and wake up rested.",
"Any products that can help with stress and make me sleep better?",
"I’ve been really stressed out, do you have anything that can help me relax and sleep?",
"Looking for something to relieve stress and help me get a good night's sleep.",
"Got any stress relief options that will also help me sleep better?",
"Struggling with sleep and stress, any suggestions?",
"Can you recommend something for stress relief that also helps with sleep?",
"Need help winding down from stress and getting some rest at night.",
"Been feeling really tense and can’t sleep, do you have anything for that?",
"Anything that will help with stress and help me fall asleep easier?",
"I’m looking for stress relief and better sleep at the same time, any products?",
"I can’t sleep at night, do you have anything for that?",
"Been feeling super stressed out lately, what can help me relax?",
"Any products that help with falling asleep faster?",
"Having trouble unwinding after a stressful day, anything you recommend?",
"Can’t seem to get a good night’s sleep, any natural remedies?",
"I need something to help me calm down and get better rest at night.",
"Been struggling with stress and it’s affecting my sleep, any solutions?",
"Looking for something to relax and get a deeper sleep.",
"Anything that can help me sleep better without feeling groggy?",
"Been under a lot of stress recently, need something to help me relax.",
"Any recommendations for getting a restful sleep?",
"I’m feeling stressed and need something to help me chill out.",
"Looking for something to help me sleep better, any tips?",
"Can’t fall asleep easily lately, do you have any natural options?",
"Need something to help with my stress and anxiety, any suggestions?",
"Any products for better sleep and stress relief together?",
"I feel exhausted, but can’t seem to relax enough to sleep.",
"Been really stressed, need something to help me wind down.",
"Looking for something to help with both sleep and stress relief.",
"Not sleeping well due to stress, what can I try?",
"Any products that help with both stress and better sleep?",
"Can’t sleep well because of stress, any advice?",
"Been dealing with anxiety lately, looking for something to help me relax.",
"Need help with sleep problems, anything natural I can try?",
"I’ve been feeling super stressed, any products that help me unwind?",
"Looking for something to calm my mind before bed.",
"Need something to help with sleep and also reduce my stress.",
"Struggling to get quality sleep, I think stress is the cause.",
"Could use something to relax after a stressful day, suggestions?",
"Can’t fall asleep easily, what can I take to help me unwind?",
"Any products that help me sleep better and reduce stress?",
"Having trouble sleeping, think it’s the stress. Any suggestions?",
"Looking for something to help me relax after a long stressful day.",
"Can’t sleep properly lately, what can help with that and stress?",
"Been feeling a bit anxious and can’t sleep well, need some relief.",
"Something for sleep would be great, also stressed all the time.",
"Any good products to help with sleep and calm my nerves?",
"Sleep is hard with all this stress, need something natural.",
"I need help sleeping through the night, also dealing with stress.",
"Feel stressed and can’t sleep, what can I use to calm down?",
"Can’t seem to unwind at night, need something for better sleep and stress relief.",
"Feeling really stressed and haven’t slept well in days. Any recommendations?",
"Any suggestions for calming down and getting some good sleep?",
"Been struggling with sleep and stress, what can I try?",
"Can’t seem to relax at night. Need help with both stress and sleep.",
"Looking for something to help me sleep better and reduce anxiety.",
"Sleep’s been off lately, stress is a big factor, anything to help?",
"Need to de-stress and sleep better, do you have anything for that?",
"Feeling a little overwhelmed, looking for something to help with stress and sleep.",
"Any advice on how to manage stress and improve sleep quality?",
"Looking for something to support me through menopause, any recommendations?",
"Can you suggest products for pregnancy that are safe and effective?",
"Struggling with hormonal changes, what should I try for balance?",
"Any advice on products that help with menopause symptoms?",
"Pregnancy’s been tough, need something to help with energy and overall wellness.",
"Looking for natural ways to manage menopause symptoms like hot flashes.",
"Can you recommend something to help with pregnancy fatigue and mood swings?",
"Any supplements for hormonal balance during pregnancy?",
"Need help with managing menopause symptoms, what should I consider?",
"Looking for a product that helps with post-pregnancy recovery and wellness.",
"Looking for something to help with pregnancy nausea, any ideas?",
"Can you recommend products for balancing hormones during menopause?",
"Need something to boost my energy while pregnant, what do you suggest?",
"Any tips for managing stress and mood swings during menopause?",
"Pregnancy has been hard on my body, any supplements to help with recovery?",
"What products can help with hot flashes and night sweats during menopause?",
"Struggling with my skin during pregnancy, need something to help.",
"Can you recommend anything for postpartum health and energy?",
"Looking for a supplement that supports fertility and reproductive health.",
"Any recommendations for easing cramps and bloating during pregnancy?",
"Are there any products to help with pregnancy fatigue?",
"Can you suggest something for menopausal symptoms like hot flashes?",
"Looking for something to support my body during pregnancy, any ideas?",
"Do you have any products for balancing hormones post-pregnancy?",
"Need a supplement to help with sleep during menopause.",
"Struggling with skin changes during pregnancy, any recommendations?",
"Looking for something to relieve period pain and cramps.",
"Can you suggest a product to support my bones during menopause?",
"What’s good for energy levels during the third trimester of pregnancy?",
"Any products that can help with mood swings during menopause?",
"Do you have anything for pregnancy-related back pain?",
"Can you recommend a product to boost energy during my pregnancy?",
"Looking for something to help with hot flashes during menopause.",
"Any products for joint pain during pregnancy?",
"Do you have supplements for skin and hair health during pregnancy?",
"Is there anything to help with cramps during my period?",
"Can you suggest something for bloating and digestion during menopause?",
"Looking for products to help me sleep better during pregnancy.",
"Any products for balancing hormones post-pregnancy?",
"Can you recommend something for menopause-related weight gain?",
"Is there anything to help with pregnancy nausea?",
"Can you recommend something to support bone health during menopause?",
"Looking for products to ease premenstrual mood swings.",
"Do you have anything to help with night sweats during menopause?",
"Any supplements to support my skin during pregnancy?",
"Can you suggest something for energy during the first trimester?",
"I'm looking for a natural remedy for hot flashes.",
"Do you have anything to help with postpartum recovery?",
"Any products to help with pelvic pain during pregnancy?",
"Looking for a supplement to help with hormonal imbalance post-pregnancy.",
"Do you have anything to help with my menopause symptoms?",
"Looking for a supplement for pregnancy fatigue.",
"Any products to help with hormonal acne?",
"Can you recommend something for hot flashes?",
"Is there something to ease menstrual cramps?",
"I'm pregnant and feeling really low on energy, what can I take?",
"Looking for a natural remedy to support my hormones post-pregnancy.",
"Any advice for improving sleep during pregnancy?",
"Do you have anything for mood swings during menopause?",
"Can you suggest something for stronger nails during pregnancy?",
"Any supplements to help with pregnancy-related nausea?",
"Looking for something for menopause weight gain.",
"Can you recommend something for hormonal imbalance?",
"I'm having trouble with my periods, anything that can help?",
"Is there something to support bone health during menopause?",
"Looking for a supplement to boost my fertility.",
"Do you have anything to help with perimenopause symptoms?",
"Can you recommend a product for post-pregnancy recovery?",
"Any advice for managing stress during pregnancy?",
"Do you have anything for vaginal dryness after menopause?",
"Need help with pregnancy-related fatigue, anything that works?",
"Looking for something to help with menopause hot flashes.",
"Can you recommend something for PMS symptoms?",
"Is there a supplement for improving fertility naturally?",
"Any products for managing anxiety during menopause?",
"Looking for post-pregnancy supplements for energy.",
"Can you recommend something for hormonal acne?",
"Is there anything for better sleep during pregnancy?",
"Can you help with maintaining bone health during menopause?",
"Looking for supplements to support a healthy pregnancy.",
"Looking for something to help balance my hormones.",
"Any recommendations for vitamins for postpartum health?",
"Need advice on managing menopause symptoms naturally.",
"Is there something to help with mood swings during PMS?",
"Looking for natural supplements to support fertility.",
"Can you recommend something for pregnancy-related nausea?",
"Any products that can help with vaginal dryness during menopause?",
"Looking for something to improve bone density post-menopause.",
"Can you suggest something for balancing estrogen levels?",
"Any supplements to ease the pain of menstrual cramps?",
"Looking for something to ease hot flashes during menopause.",
"Can you recommend something to help with my period cramps?",
"Are there any supplements to help with post-pregnancy recovery?",
"Do you have anything for hormone balance after 40?",
"Any products that help with low energy during pregnancy?",
"Looking for vitamins to support my skin during menopause.",
"Can you recommend something to regulate my cycle?",
"What's best for managing mood swings before my period?",
"Any supplements to help with hair thinning during menopause?",
"Can you suggest something for easing bloating during my period?"





    ],
    "Category": [
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
        "Bone & Joint Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
        "Gut Health",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
        "Immune Support",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
        "Energy & Vitality",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
        "Sleep & Relaxation",
"Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
"Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
"Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
"Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
"Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
"Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
"Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
"Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
"Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health",
        "Women's Health"
    ]
}

# Convert data to DataFrame
df = pd.DataFrame(data)

# Create a pipeline with a CountVectorizer and a MultinomialNB classifier
model = make_pipeline(
    CountVectorizer(),
    MultinomialNB()
)

# Fit the model with the training data
model.fit(df['Input'], df['Category'])

# Mock products dictionary - each category has a list of products
products = {
    "Bone & Joint Health": ["Omega-3", "Glucosamine", "Calcium"],
    "Gut Health": ["Probiotics", "Digestive Enzymes", "Fiber"],
    "Immune Support": ["Vitamin C", "Zinc", "Echinacea"],
    "Energy & Vitality": ["B12", "Ginseng", "Iron"],
    "Sleep & Relaxation": ["Magnesium", "Melatonin", "Valerian Root"],
    "Women's Health": ["Folic Acid", "Iron", "Omega-3 for Pregnancy"],
    "Sports Nutrition": ["Whey Protein", "BCAAs", "Creatine"]
}

@app.route('/predict', methods=['POST'])
def predict():
    data = request.json
    input_text = data.get('text', '')
    
    if not input_text:
        return jsonify({"error": "No input provided"}), 400

    prediction = model.predict([input_text])
    category = prediction[0]
    recommended_products = products.get(category, [])

    return jsonify({
        "input": input_text,
        "category": category,
        "recommended_products": recommended_products
    })

if __name__ == '__main__':
    app.run(debug=True)

# Function to test the model with new inputs and recommend products
'''def test_model(input_text):
    prediction = model.predict([input_text])
    category = prediction[0]
    print(f"Input: {input_text}")
    print(f"Category: {category}")
    print(f"Recommended Products: {', '.join(products[category])}")

# Test the model with some inputs
test_inputs = [
    "I need something for sleep"
]

for test_input in test_inputs:
    test_model(test_input) '''